# Generated by Django 3.2.11 on 2022-02-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_restaurant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/menus/background/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/restaruants/background/'),
        ),
    ]
